package tw.yourcompany.cgmbridge.core.platform

import android.app.ActivityManager
import android.content.Context
import android.net.Uri
import android.os.Build
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import tw.yourcompany.cgmbridge.core.db.AppDatabase
import java.io.BufferedOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/**
 * Creates an "App Diagnostics" ZIP suitable for normal users.
 *
 * Why "App Diagnostics" instead of full "device bugreport"?
 * - Full bugreports (system logs / full logcat / dumpsys) require privileged permissions
 *   on most Android devices and cannot be collected by a regular app.
 * - This exporter collects what an app can reliably access:
 *   - app logs (Room event_log)
 *   - app data snapshot (recent bg_reading)
 *   - thread stack traces (Thread.getAllStackTraces)
 *   - device/app metadata
 *   - memory info
 */
object BugReportExporter {

    fun defaultFileName(): String {
        val fmt = SimpleDateFormat("yyyyMMdd-HHmmss", Locale.US)
        return "cgmbridge-report-${fmt.format(Date())}.zip"
    }

    suspend fun export(context: Context, target: Uri) = withContext(Dispatchers.IO) {
        val resolver = context.contentResolver
        resolver.openOutputStream(target)?.use { rawOut ->
            ZipOutputStream(BufferedOutputStream(rawOut)).use { zip ->
                writeText(zip, "README.txt", readmeText())
                writeText(zip, "app_state.json", buildAppStateJson(context))
                writeText(zip, "threads.txt", dumpThreads())
                writeText(zip, "prefs.json", dumpPrefs(context))
                writeText(zip, "memory.txt", dumpMemory(context))
                writeText(zip, "event_log.csv", dumpEventLogCsv(context))
                writeText(zip, "bg_reading.csv", dumpBgReadingCsv(context))
                writeText(zip, "system_info.txt", dumpSystemInfo(context))
                val logcat = try { dumpLogcat() } catch (_: Throwable) { null }
                if (logcat != null) {
                    writeText(zip, "logcat.txt", logcat)
                }
            }
        } ?: throw IllegalStateException("Cannot open output stream for selected location")
    }

    private fun writeText(zip: ZipOutputStream, name: String, content: String) {
        val entry = ZipEntry(name)
        zip.putNextEntry(entry)
        val bytes = content.toByteArray(Charsets.UTF_8)
        zip.write(bytes)
        zip.closeEntry()
    }

    private fun readmeText(): String = buildString {
        appendLine("CgmBridge App Diagnostics")
        appendLine("========================")
        appendLine()
        appendLine("This ZIP was generated by the app (normal user mode).")
        appendLine("It contains app-scoped diagnostics: app logs, thread stacks, app settings snapshot, and memory info.")
        appendLine()
        appendLine("If you need a FULL SYSTEM bugreport (device logs, system dumps, full logcat):")
        appendLine("1) Enable Developer Options (tap Build number 7 times)")
        appendLine("2) Open Developer options → Take bug report")
        appendLine("3) Share the generated bugreport ZIP")
        appendLine()
    }

    private fun buildAppStateJson(context: Context): String {
        val pm = context.packageManager
        val pkg = context.packageName
        val pi = pm.getPackageInfo(pkg, 0)
        val versionName = pi.versionName ?: ""
        val versionCode = if (Build.VERSION.SDK_INT >= 28) pi.longVersionCode else @Suppress("DEPRECATION") pi.versionCode.toLong()

        val now = System.currentTimeMillis()
        return """{
  "generatedAtMs": $now,
  "app": {
    "package": "$pkg",
    "versionName": "$versionName",
    "versionCode": $versionCode
  },
  "device": {
    "manufacturer": "${Build.MANUFACTURER}",
    "model": "${Build.MODEL}",
    "sdkInt": ${Build.VERSION.SDK_INT},
    "release": "${Build.VERSION.RELEASE}"
  }
}"""
    }

    private fun dumpThreads(): String {
        val sb = StringBuilder()
        val all = Thread.getAllStackTraces()
        sb.append("Thread count: ").append(all.size).append("\n\n")
        for ((t, st) in all) {
            sb.append("--- ").append(t.name)
                .append(" (id=").append(t.id)
                .append(", state=").append(t.state)
                .append(") ---\n")
            for (e in st) sb.append("    at ").append(e.toString()).append("\n")
            sb.append("\n")
        }
        return sb.toString()
    }

    private fun dumpPrefs(context: Context): String {
        val sp = context.getSharedPreferences("bridge_prefs", Context.MODE_PRIVATE)
        val all = sp.all
        val sb = StringBuilder()
        sb.append("{\n")
        val keys = all.keys.sorted()
        for ((i, k) in keys.withIndex()) {
            val v = all[k]
            val valueStr = when (v) {
                is String -> "\"${escapeJson(v)}\""
                is Boolean, is Int, is Long, is Float -> v.toString()
                null -> "null"
                else -> "\"${escapeJson(v.toString())}\""
            }
            sb.append("  \"").append(escapeJson(k)).append("\": ").append(valueStr)
            if (i != keys.lastIndex) sb.append(',')
            sb.append("\n")
        }
        sb.append("}\n")
        return sb.toString()
    }

    private fun dumpMemory(context: Context): String {
        val am = context.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
        val mi = ActivityManager.MemoryInfo()
        am.getMemoryInfo(mi)

        val rt = Runtime.getRuntime()
        val used = rt.totalMemory() - rt.freeMemory()

        return buildString {
            appendLine("Runtime used bytes: $used")
            appendLine("Runtime free bytes: ${rt.freeMemory()}")
            appendLine("Runtime total bytes: ${rt.totalMemory()}")
            appendLine("Runtime max bytes: ${rt.maxMemory()}")
            appendLine()
            appendLine("System MemoryInfo:")
            appendLine("  availMem: ${mi.availMem}")
            appendLine("  totalMem: ${mi.totalMem}")
            appendLine("  threshold: ${mi.threshold}")
            appendLine("  lowMemory: ${mi.lowMemory}")
            appendLine()
            appendLine("ActivityManager memoryClass: ${am.memoryClass} MB")
            appendLine("ActivityManager largeMemoryClass: ${am.largeMemoryClass} MB")
        }
    }

    private suspend fun dumpEventLogCsv(context: Context): String {
        val db = AppDatabase.get(context)
        val rows = db.eventLogDao().latestOnce(2000)
        val sb = StringBuilder()
        sb.appendLine("timestampMs,level,tag,message")
        for (r in rows) {
            sb.append(r.timestampMs).append(',')
            sb.append(escapeCsv(r.level)).append(',')
            sb.append(escapeCsv(r.tag)).append(',')
            sb.append(escapeCsv(r.message)).append("\n")
        }
        return sb.toString()
    }

    private suspend fun dumpBgReadingCsv(context: Context): String {
        val db = AppDatabase.get(context)
        val rows = db.bgReadingDao().latestOnce(2000)
        val sb = StringBuilder()
        sb.appendLine("timestampMs,calculatedValueMgdl,direction,sourcePackage,sensorStatus,alertText")
        for (r in rows) {
            sb.append(r.timestampMs).append(',')
            sb.append(r.calculatedValueMgdl).append(',')
            sb.append(escapeCsv(r.direction)).append(',')
            sb.append(escapeCsv(r.sourcePackage)).append(',')
            sb.append(escapeCsv(r.sensorStatus ?: "")).append(',')
            sb.append(escapeCsv(r.alertText ?: "")).append("\n")
        }
        return sb.toString()
    }

    private fun dumpSystemInfo(context: Context): String {
        val sb = StringBuilder()
        // Battery info
        try {
            val bm = context.getSystemService(Context.BATTERY_SERVICE) as? android.os.BatteryManager
            if (bm != null) {
                val level = bm.getIntProperty(android.os.BatteryManager.BATTERY_PROPERTY_CAPACITY)
                sb.appendLine("Battery level: $level%")
            }
        } catch (_: Throwable) {}
        // Network info
        try {
            val cm = context.getSystemService(Context.CONNECTIVITY_SERVICE) as? android.net.ConnectivityManager
            val active = cm?.activeNetworkInfo
            if (active != null) {
                sb.appendLine("Network type: ${active.typeName}")
                sb.appendLine("Network connected: ${active.isConnected}")
            }
        } catch (_: Throwable) {}
        // Storage info
        try {
            val stat = android.os.StatFs(context.filesDir.absolutePath)
            val bytesAvailable = stat.availableBytes
            val bytesTotal = stat.totalBytes
            sb.appendLine("Storage available: $bytesAvailable bytes")
            sb.appendLine("Storage total: $bytesTotal bytes")
        } catch (_: Throwable) {}
        return sb.toString()
    }

    private fun dumpLogcat(): String? {
        // Try to get logcat output for this process only
        return try {
            val process = Runtime.getRuntime().exec(arrayOf("logcat", "-d", "-v", "time", "--pid", android.os.Process.myPid().toString()))
            process.inputStream.bufferedReader().use { it.readText() }
        } catch (e: Exception) {
            // If logcat is restricted, return null to skip
            null
        }
    }

    private fun escapeCsv(s: String): String {
        val needsQuotes = s.contains(',') || s.contains('"') || s.contains("\n") || s.contains("\r")
        val escaped = s.replace("\"", "\"\"")
        return if (needsQuotes) "\"$escaped\"" else escaped
    }

    private fun escapeJson(s: String): String {
        return s
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t")
    }
}
